version: 2.1
jobs:
  build:
    docker: 
      - image: ubuntu:20.04
    steps:
      - checkout # check out the code in the project directory
      - run: echo $DOTENV | base64 --decode > .env
      - run: sudo apt-get update && sudo apt-get install -y wget jq redis-tools
      - run: ./test/test.sh

