version: 2.1
jobs:
  build:
    docker: 
      - image: cimg/base:2021.04
    steps:
      - checkout # check out the code in the project directory
      - run: echo $DOTENV | base64 --decode > .env
      - run: apt-get update && apt-get install -y wget jq redis-tools
      - run: ./test/test.sh

